### ISSUE TITLE
There's a bug in the contract part in search jobs

### ISSUE THREAD

**Issue by vineel31** [CSC510-SE-Uddharsh-Vineel-Chandrakant/G50-WolfTrack7.0#3]
![image](https://github.com/user-attachments/assets/8eb1f4ad-b8dd-4357-92c8-e086e0836e67)
There's a bug in the contract part in search jobs

**Comment by vineel31** [comment]
one of us have to fix this

**Comment by konetichandrakant** [comment]
I will take it over. Else you can take over it I will help you to debug and trace that issue.

I see they have called ", ".join() function which is not correct we need to remove it and write our own logic for this part.

**Comment by vineel31** [comment]
yes
